### ISSUE TITLE
Error allocating remote code buffer

### ISSUE THREAD

**Issue by hatRiot** [googleprojectzero/TinyInst#9]
Using LiteCov within another project on a 32-bit platform. `RemoteAllocateNear` and `RemoteAllocateBefore` both use uint64's, which led `RemoteAllocateBefore` to receive the wrong values. This function still fails to allocate (returns null) if I change these to `size_t`, but it seems like it may not have been tested on 32-bit?

**Comment by ifratric** [comment]
Hey, can you give me some more details / example of where exactly you get the wrong values. uint64s are indeed used on all platforms, but I thought the values contained in these on 32-bit would always be smaller than the maximum size_t and thus safe to cast (not sure if this is what you meant or something else), but maybe I missed something?

A 32-bit TinyInst was tested and working, but some changes were made recently to allocation in order to build multiplatform support, so it's possible something broke. I'm going to take a closer look next week.

In the meantime, note that a 64-bit build of TinyInst should be able to work against 32-bit targets as well as 64-bit. (If a whole system is 32-bit, then that's a different thing I guess).

**Comment by hatRiot** [comment]
The whole system is indeed 32-bit. You're right though, they do seem to cast appropriately on second look. The issue must be somewhere else.

What seems to be happening is `RemoteAllocateBefore` makes 2-3 attempts to find a free region, discovers they're all `MEM_COMMIT` or `MEM_RESERVE`, then bails. Perhaps a `RemoteAllocateAfter` implementation is more critical for 32-bit builds than x64? I admit to not quite understanding the intent of this code enough to implement the function myself.

I'll work towards porting things to 64-bit and retry from there. I suspect there's something funky with 32-bit systems going on, though.

**Comment by ifratric** [comment]
What are the min_address and max_address in RemoteAllocateBefore() when it gets called? If the range is really low, then it's indeed possible that there is no free memory region of sufficient size there, in which case the solution would indeed be to implement RemoteAllocateAfter (which should have been there in the first place and the only reason it isn't is that RemoteAllocateBefore always worked for me).

**Comment by hatRiot** [comment]
Here's some debug output I added in:
```
RemoteAllocateBefore: Min:0 Max:c50000 Size:005a0000
memstate: 00002000
Current code becomes: 00c50000
memstate: 00001000
Current code becomes: 006b0000
memstate: 00002000
Current code becomes: 00110000
break
```

**Comment by ifratric** [comment]
Thanks for the info! That is indeed quite low and RemoteAllocateAfter() implementation is needed to handle such cases. Stay tuned :-)

**Comment by ifratric** [comment]
Should be fixed now. Tentatively closing the issue.

**Comment by hatRiot** [comment]
That did the trick; thank you!
